# Generated by Django 3.2.8 on 2021-10-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdata',
            name='csv_result',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='json_result',
        ),
    ]
