# Generated by Django 3.2.8 on 2021-10-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211007_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdata',
            name='user',
        ),
    ]
